version: 2

defaults: &defaults
  docker:
    - image: circleci/python:2.7

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint
      - test-unit

jobs:
  lint:
    << : *defaults

    steps:
      - checkout
      - run: sudo pip install flake8 codecov pep8-naming
      - run: sudo make lint

  test-unit:
    << : *defaults

    steps:
      - checkout
      - run: sudo make test
